### PR TITLE
fix(devTipSchema): typo fixed & updated references

### LINKED ISSUE #28: [BUG] Minor spelling update
### Description

https://github.com/Pradumnasaraf/OpenSource-API/blob/main/models/devTipShhema.js

The filename is misspelled.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by meetwithyash**
## 🛠️ Fixes Issue

Closes #28 

## 👨‍💻 Changes proposed

- [x] (  updated filename and all the references)

## ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Comment by meetwithyash** [comment]
@Pradumnasaraf , Glad I could contribute! Is there anything in this repo that I can help with?

**Comment by Pradumnasaraf** [comment]
I am not sure why the unit test is failing. The changes look good. I raised a test PR it's working fine on mine
Screenshot 2023-01-17 at 5 33 45 PM

**Comment by meetwithyash** [comment]
> 

Sure!

**Comment by Pradumnasaraf** [comment]
> > 
> 
> Sure!

It's merged now. Thank you, again.

**Pull request merged**
